export const USERS = {
	GET_ACCOUNT_BALANCE: 'USER.GET_ACCOUNT_BALANCE',
	SET_USER_ADDRESS: 'USER.SET_USER_ADDRESS',
	SET_CONNECT_ERROR: 'SET_CONNECT_ERROR',
	CLEAR_CONNECT_ERROR: 'CLEAR_CONNECT_ERROR',
};
