export const USERS = {
	GET_ACCOUNT_BALANCE: 'USER.GET_ACCOUNT_BALANCE',
	SET_USER_ADDRESS: 'USER.SET_USER_ADDRESS',
	FETCH_USER_DETAILS: 'FETCH_USER_DETAILS',
};

export const SIGNER = {
	UPDATE_CONNECT_STATUS: 'SIGNER.UPDATE_CONNECT_STATUS',
	UPDATE_LOCK_STATUS: 'SIGNER.UPDATE_LOCK_STATUS',
	SET_CONNECT_ERROR: 'SET_CONNECT_ERROR',
	CLEAR_CONNECT_ERROR: 'CLEAR_CONNECT_ERROR',
};

export const KEY_MANAGER = {
	FETCH_KEY_MANAGER_DETAILS: 'FETCH_KEY_MANAGER_DETAILS',
};
