export const DEPLOY = {
	PUT_DEPLOY: 'DEPLOY.PUT_DEPLOY',
	DEPLOY_CONTRACT: 'DEPLOY.DEPLOY_CONTRACT',
	GET_DEPLOYS: 'DEPLOY.GET_DEPLOYS',
};

export const USERS = {
	GET_ACCOUNT_BALANCE: 'USER.GET_ACCOUNT_BALANCE',
	SET_USER_ADDRESS: 'USER.SET_USER_ADDRESS',
	FETCH_USER_DETAILS: 'USER.FETCH_USER_DETAILS',
};

export const SIGNER = {
	UPDATE_CONNECT_STATUS: 'SIGNER.UPDATE_CONNECT_STATUS',
	UPDATE_LOCK_STATUS: 'SIGNER.UPDATE_LOCK_STATUS',
	SET_CONNECT_ERROR: 'SIGNER.SET_CONNECT_ERROR',
	CLEAR_CONNECT_ERROR: 'SIGNER.CLEAR_CONNECT_ERROR',
};

export const KEY_MANAGER = {
	FETCH_KEY_MANAGER_DETAILS: 'KEY_MANAGER.FETCH_KEY_MANAGER_DETAILS',
	PUT_WEIGHT_DEPLOY: 'KEY_MANAGER.PUT_WEIGHT_DEPLOY',
	DEPLOY_KEY_MANAGER_CONTRACT: 'KEY_MANAGER.DEPLOY_KEY_MANAGER_CONTRACT',
	UPDATE_LOCAL_STORAGE: 'KEY_MANAGER.UPDATE_LOCAL_STORAGE',
	GET_LOCAL_STORAGE: 'KEY_MANAGER.GET_LOCAL_STORAGE',
	GET_DEPLOYS_STATUS: 'KEY_MANAGER.GET_DEPLOYS_STATUS',
};
